DATE_COLUMN = ''
COW_COLUMN = ''
ANIMAL_TOTAL_COLUMN = ''
AFILAB_TOTAL_COLUMN = ''
AL_FEATURES = []

AL_Y = ''

AL_G_FEATURES = []
AL_B_FEATURES = []

AL_TRAIN_DAYS = 10
AL_TEST_DAYS = 14
AL_N_INIT = 2
AL_N_INSTANCES = 2
AL_N_CLUSTERS = 10 * AL_N_INSTANCES
AL_BINS = 8